backend = "glx";
vsync = true;

corner-radius = 15;
rounded-corners-exclude = [
  "class_g = 'awesome'"
];

blur-method = "dual_kawase";
blur-strength = 3;
blur-background = true;
blur-background-frame = false;
blur-background-fixed = false;


opacity-rule = [
  "90:class_g = 'kitty'"
];

# Exclude application to be blur

shadow = false;
fading = true;
fade-delta = 4;
use-damage = true;

transparent-clipping = false;
